import Link from 'next/link'
import { Badge } from '@/components/ui'

const navItems = [
  { href: '/dashboard', label: 'Dashboard' },
  { href: '/dashboard/settings', label: 'Settings' },
]

export function DemoBanner() {
  return (
    <div className="border-b border-emerald-200 bg-emerald-50 px-4 py-2 text-center text-xs font-medium text-emerald-800">
      MVP workspace generated by NEXUS OS with local operating data and paid roadmap expansion.
    </div>
  )
}

export function AppSidebar() {
  return (
    <aside className="hidden min-h-screen w-64 border-r border-zinc-200 bg-white p-5 lg:block">
      <div className="mb-8">
        <p className="text-lg font-black text-zinc-950">Review Reply Bot</p>
        <Badge className="mt-2">MVP</Badge>
      </div>
      <nav className="space-y-1">
        {navItems.map(item => (
          <Link key={item.href} href={item.href} className="block rounded-lg px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100 hover:text-zinc-950">
            {item.label}
          </Link>
        ))}
      </nav>
    </aside>
  )
}

export function AppHeader() {
  return (
    <header className="sticky top-0 z-20 border-b border-zinc-200 bg-white/90 px-4 py-3 backdrop-blur">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm font-semibold text-zinc-950">Review Reply Bot</p>
          <p className="text-xs text-zinc-500">Generated operating dashboard</p>
        </div>
        <Badge>Ready</Badge>
      </div>
    </header>
  )
}
